### ISSUE TITLE
BUG in reports (error from)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#481]
With last develop version.

When we click on one of the date, we got this:

![capture d ecran 2017-02-05 a 11 03 49](https://cloud.githubusercontent.com/assets/12907102/22625322/ee6b5e36-eb92-11e6-8c20-d1ccf4f4a83c.png)

![capture d ecran 2017-02-05 a 11 03 15](https://cloud.githubusercontent.com/assets/12907102/22625323/f128f354-eb92-11e6-972d-f6d5561a8293.png)

**Comment by asuweb** [comment]
I think the same bug is also present when you try to run a report

**Comment by stefaweb** [comment]
Yes

![capture d ecran 2017-02-05 a 11 13 10](https://cloud.githubusercontent.com/assets/12907102/22625364/a2214700-eb94-11e6-9adc-00d96c73eb41.png)

**Comment by asuweb** [comment]
I noticed it yesterday when I mistakenly pushed the develop branch to my live site - then spent 2 hours rebuilding the live site into a working version.

**Comment by stefaweb** [comment]
For the fun, I'me still using a custom v1.0.3 on my own production server. As I'm managing 20/25000 mails par day, I'm very conservative. ;-)

**Comment by stefaweb** [comment]
Another one.

In all reports with graph.

![capture d ecran 2017-02-05 a 12 18 59](https://cloud.githubusercontent.com/assets/12907102/22625691/a560cbb2-eb9d-11e6-98a7-433cf043846d.png)

**Comment by Skywalker-11** [comment]
error with the graphes should only occure in rep_top_sender* and rep_top_recepient* and is typo `$count` instead of `count`. it is fixed in #474 and #477

**Comment by Skywalker-11** [comment]
Sorry. I created that other bug when refactoring.Will be fixed by #483.

**Comment by stefaweb** [comment]
Done.

**Comment by stefaweb** [comment]
I still have the problem with last develop version.

rep_top_senders_by_quantity.php and others.

![capture d ecran 2017-02-07 a 15 49 55](https://cloud.githubusercontent.com/assets/12907102/22696208/78c2bd2a-ed4d-11e6-8253-455dec4214c4.png)

**Comment by Skywalker-11** [comment]
that will be fixed by #474 or #477 but if needed I can create an additional pr for this

**Comment by stefaweb** [comment]
Ok, no problem.
See my comment in #497.

**Comment by stefaweb** [comment]
Done.
